name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # install this on VM
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0

      # testing the app
      - name: dotnet test
        run: dotnet test --configuration Release

      - name: dotnet publish
        # sada ispod u run ne moras da kazes src/<fajlovi folderi>,
        # kao sto si rekao za tu command iznad koje je u komentaru
        working-directory: src/
        # -o artifacts - output artifacts - artifacts je folder
#        run: dotnet publish src/GitHubActionsDotNet.Api/GitHubActionsDotNet.Api.csproj --configuration Release -o artifacts
        run: dotnet publish /GitHubActionsDotNet.Api/GitHubActionsDotNet.Api.csproj --configuration Release -o ../artifacts
