name: PR Verify

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: PR Verify
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # install this on VM
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0
      #       compile app
      - name: Build with dotnet
        run: dotnet build --configuration Release
