name: Secrets

on:
  pull_request:
    branches:
      # ["main"]
      - main

env:
  API_CSPROJ_PATH: "./src/GitHubActionsDoeNet.Api/GitHubActionsDoeNet.Api.csproj"

jobs:
  # ovo je job ID, moze da bude sta oces
  secrets:
    name: Secrets Demo 1
    runs-on: ubuntu-latest
    # env na nivou job-a
    env:
      JOB_NAME: "secrets"

    steps:
      - name: echo env variable
        run: echo "$JOB_NAME is this $API_CSPROJ_PATH"

  new_job:
    name: Secrets Demo 2
    runs-on: ubuntu-latest
    # env na nivou job-a
    env:
      JOB_NAME: "new_job"

    steps:
      - name: echo env variable
        run: echo "$JOB_NAME is this $API_CSPROJ_PATH"
