name: Secrets

on:
  pull_request:
    branches:
      # ["main"]
      - main

env:
  API_CSPROJ_PATH: "./src/GitHubActionsDoeNet.Api/GitHubActionsDoeNet.Api.csproj"

jobs:
  # ovo je ID, moze da bude sta oces
  secrets:
    name: Secrets Demo
    runs-on: ubuntu-latest

    steps:
      - name: echo env variable
        run: echo "$API_CSPROJ_PATH
