name: Secrets

on:
  pull_request:
    branches:
      # ["main"]
      - main

env:
  API_CSPROJ_PATH: "./src/GitHubActionsDoeNet.Api/GitHubActionsDoeNet.Api.csproj"

jobs:
  # ovo je job ID, moze da bude sta oces
  secrets:
    name: Secrets Demo 1
    runs-on: ubuntu-latest

    steps:
      - name: echo env variable
        # secrets.SECRET_API_KEY zamisli da je neki secret key, kao api key
        # to se namesta u github secrets
        # na njihovom sajtu.
        run: echo "${{secrets.SECRET_API_KEY}} is this $API_CSPROJ_PATH"
